/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package tech.pegasys.jckzg.swig;

public class G2 {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected G2(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(G2 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CKzgJNI.delete_G2(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static G2 from_compressed(byte[] arr) {
    long cPtr = CKzgJNI.G2_from_compressed(arr);
    return (cPtr == 0) ? null : new G2(cPtr, false);
  }

}
