/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package tech.pegasys.jckzg.swig;

public class LongVector extends java.util.AbstractList<Long> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected LongVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(LongVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CKzgJNI.delete_LongVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public LongVector(long[] initialElements) {
    this();
    reserve(initialElements.length);

    for (long element : initialElements) {
      add(element);
    }
  }

  public LongVector(Iterable<Long> initialElements) {
    this();
    for (long element : initialElements) {
      add(element);
    }
  }

  public Long get(int index) {
    return doGet(index);
  }

  public Long set(int index, Long e) {
    return doSet(index, e);
  }

  public boolean add(Long e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, Long e) {
    modCount++;
    doAdd(index, e);
  }

  public Long remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public LongVector() {
    this(CKzgJNI.new_LongVector__SWIG_0(), true);
  }

  public LongVector(LongVector other) {
    this(CKzgJNI.new_LongVector__SWIG_1(LongVector.getCPtr(other), other), true);
  }

  public long capacity() {
    return CKzgJNI.LongVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    CKzgJNI.LongVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return CKzgJNI.LongVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    CKzgJNI.LongVector_clear(swigCPtr, this);
  }

  public LongVector(int count, long value) {
    this(CKzgJNI.new_LongVector__SWIG_2(count, value), true);
  }

  private int doSize() {
    return CKzgJNI.LongVector_doSize(swigCPtr, this);
  }

  private void doAdd(long x) {
    CKzgJNI.LongVector_doAdd__SWIG_0(swigCPtr, this, x);
  }

  private void doAdd(int index, long x) {
    CKzgJNI.LongVector_doAdd__SWIG_1(swigCPtr, this, index, x);
  }

  private long doRemove(int index) {
    return CKzgJNI.LongVector_doRemove(swigCPtr, this, index);
  }

  private long doGet(int index) {
    return CKzgJNI.LongVector_doGet(swigCPtr, this, index);
  }

  private long doSet(int index, long val) {
    return CKzgJNI.LongVector_doSet(swigCPtr, this, index, val);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    CKzgJNI.LongVector_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
