/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package tech.pegasys.jckzg.swig;

public class Poly {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Poly(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Poly obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CKzgJNI.delete_Poly(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Poly(int length) {
    this(CKzgJNI.new_Poly__SWIG_0(length), true);
  }

  public Poly(FrVector coeff) {
    this(CKzgJNI.new_Poly__SWIG_1(FrVector.getCPtr(coeff), coeff), true);
  }

  public Poly long_div(Poly divisor) {
    long cPtr = CKzgJNI.Poly_long_div(swigCPtr, this, Poly.getCPtr(divisor), divisor);
    return (cPtr == 0) ? null : new Poly(cPtr, false);
  }

  public Fr eval(Fr x) {
    return new Fr(CKzgJNI.Poly_eval(swigCPtr, this, Fr.getCPtr(x), x), true);
  }

}
